#!/usr/bin/env node
// Build pipeline for Lazyfox.
//
//   1. Compile the Go core to core/js/core.wasm, base64 it, and write
//      src/shared/wasm-embed.ts (gitignored; the wasm is embedded into every
//      bundle so each context is self-contained). The wasm is embedded raw (no
//      gzip): decompression would need DecompressionStream/pako, which are not
//      guaranteed in every context, whereas atob() + WebAssembly.instantiate()
//      are.
//   2. esbuild-bundle each TypeScript entry (chrome helper, core bootstrap,
//      frame script, content script, background, command center, options x2,
//      popup) into dist/.
//   3. Copy static assets (manifest, HTML pages, icons, chrome css/user.js/
//      loader) from src/static/ into dist/.
//
// dist/ is committed to the repo so installers consume prebuilt output and
// users who clone don't need a Go toolchain to install.

import { execFileSync } from "node:child_process";
import { cpSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const root = resolve(dirname(fileURLToPath(import.meta.url)));

// `npm run build:dev` (node build.mjs --dev) defines __DEV__=true so the
// dev-only diagnostics compile in; the default prod build tree-shakes them
// out entirely (__DEV__=false), keeping dist/ free of debug output.
const DEV = process.argv.includes("--dev");

const BUNDLES = [
  { in: "src/chrome/main.ts", out: "dist/chrome/userChrome.uc.js" },
  { in: "src/chrome/corebootstrap.ts", out: "dist/chrome/corebootstrap.js" },
  { in: "src/chrome/frame.ts", out: "dist/chrome/frame.js" },
  { in: "src/extension/content/main.ts", out: "dist/extension/content.js" },
  { in: "src/extension/background.ts", out: "dist/extension/background.js" },
  { in: "src/extension/commandcenter.ts", out: "dist/extension/commandcenter.js" },
  { in: "src/extension/options.ts", out: "dist/extension/options.js" },
  { in: "src/extension/optionskeys.ts", out: "dist/extension/optionskeys.js" },
  { in: "src/extension/popup.ts", out: "dist/extension/popup.js" },
  { in: "src/extension/splitview.ts", out: "dist/extension/splitview.js" },
];

/* ---------- 1. wasm core ---------- */

const wasmOut = join(root, "core", "js", "core.wasm");
console.log("[wasm] building core.wasm (GOOS=js GOARCH=wasm)...");
execFileSync("go", ["build", "-ldflags=-s -w", "-o", wasmOut, "./core/js"], {
  cwd: root,
  env: { ...process.env, GOOS: "js", GOARCH: "wasm" },
  stdio: "inherit",
});
const wasmBytes = readFileSync(wasmOut);
const b64 = wasmBytes.toString("base64");
writeFileSync(
  join(root, "src", "shared", "wasm-embed.ts"),
  "// GENERATED by build.mjs from core/js/core.wasm \u2014 do not edit.\n" +
    "// base64-encoded (raw, not gzip) so every bundle is self-contained and\n" +
    "// the runtime needs only atob() + WebAssembly.instantiate().\n" +
    "export const WASM_BASE64 =\n  \"" +
    b64 +
    "\";\n"
);
console.log(
  `[wasm] ${wasmBytes.length} bytes -> base64 ${b64.length}`
);

/* ---------- 2. esbuild bundles ---------- */

for (const b of BUNDLES) {
  const outfile = join(root, b.out);
  mkdirSync(dirname(outfile), { recursive: true });
  await build({
    entryPoints: [join(root, b.in)],
    bundle: true,
    outfile,
    format: "iife",
    platform: "browser",
    target: ["firefox115"],
    define: { __DEV__: DEV ? "true" : "false" },
    minify: true,
    logLevel: "info",
  });
  console.log(`[bundle] ${b.in} -> ${b.out}`);
}

/* ---------- 3. static assets ---------- */

cpSync(join(root, "src", "static", "extension"), join(root, "dist", "extension"), {
  recursive: true,
});
cpSync(join(root, "src", "static", "chrome"), join(root, "dist", "chrome"), {
  recursive: true,
});
console.log("[static] src/static/{extension,chrome} -> dist/");

console.log("\nBuild complete. dist/ is ready to install.");
