#!/usr/bin/env node
// Build pipeline for Lazyfox.
//
//   1. Compile the Go core to core/js/core.wasm, base64 it, and write
//      src/shared/wasm-embed.ts (gitignored; the wasm is embedded into every
//      bundle so each context is self-contained). The wasm is embedded raw (no
//      gzip): decompression would need DecompressionStream/pako, which are not
//      guaranteed in every context, whereas atob() + WebAssembly.instantiate()
//      are.
//   2. esbuild-bundle each TypeScript entry (chrome helper, core bootstrap,
//      frame script, content script, background, command center, options x2,
//      popup) into dist/.
//   3. Copy static assets (manifest, HTML pages, icons, chrome css/user.js/
//      loader) from src/static/ into dist/.
//
// dist/ is committed to the repo so installers consume prebuilt output and
// users who clone don't need a Go toolchain to install.

import { execFileSync } from "node:child_process";
import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";
import { zipStore } from "./scripts/amo-lib.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)));

// `npm run build:dev` (node build.mjs --dev) defines __DEV__=true so the
// dev-only diagnostics compile in; the default prod build tree-shakes them
// out entirely (__DEV__=false), keeping dist/ free of debug output.
const DEV = process.argv.includes("--dev");

const BUNDLES = [
  { in: "src/chrome/main.ts", out: "dist/chrome/userChrome.uc.js" },
  { in: "src/chrome/corebootstrap.ts", out: "dist/chrome/corebootstrap.js" },
  { in: "src/chrome/frame.ts", out: "dist/chrome/frame.js" },
  { in: "src/extension/content/main.ts", out: "dist/extension/content.js" },
  { in: "src/extension/background.ts", out: "dist/extension/background.js" },
  { in: "src/extension/commandcenter.ts", out: "dist/extension/commandcenter.js" },
  { in: "src/extension/splitpanel.ts", out: "dist/extension/splitpanel.js" },
  { in: "src/extension/options.ts", out: "dist/extension/options.js" },
  { in: "src/extension/optionskeys.ts", out: "dist/extension/optionskeys.js" },
  { in: "src/extension/popup.ts", out: "dist/extension/popup.js" },
  { in: "src/extension/setup.ts", out: "dist/extension/setup.js" },
];

/* ---------- 1. wasm core ---------- */

const wasmOut = join(root, "core", "js", "core.wasm");
console.log("[wasm] building core.wasm (GOOS=js GOARCH=wasm)...");
execFileSync("go", ["build", "-ldflags=-s -w", "-o", wasmOut, "./core/js"], {
  cwd: root,
  env: { ...process.env, GOOS: "js", GOARCH: "wasm" },
  stdio: "inherit",
});
const wasmBytes = readFileSync(wasmOut);
const b64 = wasmBytes.toString("base64");
writeFileSync(
  join(root, "src", "shared", "wasm-embed.ts"),
  "// GENERATED by build.mjs from core/js/core.wasm \u2014 do not edit.\n" +
    "// base64-encoded (raw, not gzip) so every bundle is self-contained and\n" +
    "// the runtime needs only atob() + WebAssembly.instantiate().\n" +
    "export const WASM_BASE64 =\n  \"" +
    b64 +
    "\";\n"
);
console.log(
  `[wasm] ${wasmBytes.length} bytes -> base64 ${b64.length}`
);

/* ---------- 2. esbuild bundles ---------- */

for (const b of BUNDLES) {
  const outfile = join(root, b.out);
  mkdirSync(dirname(outfile), { recursive: true });
  await build({
    entryPoints: [join(root, b.in)],
    bundle: true,
    outfile,
    format: "iife",
    platform: "browser",
    target: ["firefox115"],
    define: { __DEV__: DEV ? "true" : "false" },
    minify: true,
    logLevel: "info",
  });
  console.log(`[bundle] ${b.in} -> ${b.out}`);
}

/* ---------- 3. static assets ---------- */

cpSync(join(root, "src", "static", "extension"), join(root, "dist", "extension"), {
  recursive: true,
});
cpSync(join(root, "src", "static", "chrome"), join(root, "dist", "chrome"), {
  recursive: true,
});
console.log("[static] src/static/{extension,chrome} -> dist/");

/* ---------- 4. dev add-on / signed add-on + installer binary ---------- */

// In --dev mode we short-circuit the production release steps (AMO signing and
// the standalone installer binary rebuild). The dev installers consume the
// freshly built UNSIGNED xpi directly from dist/extension, so there is no need
// to contact AMO or recompile installer/bin every dev iteration.
if (DEV) {
  const version = JSON.parse(readFileSync(join(root, "dist", "extension", "manifest.json"), "utf8")).version;
  const unsignedOut = join(root, "dist", `lazyfox2-${version}.xpi`);
  console.log(`[dev] packaging unsigned xpi -> dist/lazyfox2-${version}.xpi`);
  zipStore(join(root, "dist", "extension"), unsignedOut);
  console.log(`\nBuild complete. dist/ is ready to install (unsigned dev add-on).`);
  process.exit(0);
}

// `npm run build:dev:installers` (node scripts/build-dev-installers.mjs)
// builds the committed per-OS DEV installer binaries (embed the unsigned xpi).
// It is a separate step from build:dev on purpose: the per-OS binaries are
// semantically "ship/dev" artifacts produced alongside the unsigned build, and
// keeping them out of the fast dev loop avoids re-cross-compiling Go on every
// iteration. Dev install flow: npm run build:dev && npm run build:dev:installers.

// Ensure a signed .xpi exists for the current extension version.
//
// Release mode (RELEASE=1, used by the master workflow): sync-signed-xpi.mjs
// downloads the AMO-signed xpi for the exact manifest version from AMO and
// writes both dist/lazyfox2-<ver>.xpi and -signed.xpi. It reuses a committed
// signed xpi when already current, so it is deterministic (version comes from
// the manifest) and never fabricates or guesses.
//
// Normal mode: amo-sign.mjs reuses the committed signed artifact offline, or
// auto-submits a NEW version to AMO when the version is bumped (see that script
// for details). The installer installs this signed xpi verbatim, which is what
// makes the add-on load on stable Firefox (it already ships the AMO signature
// block).
if (process.env.RELEASE === "1") {
  console.log("[sign] syncing AMO-signed xpi for the current version…");
  execFileSync(process.execPath, [join(root, "scripts", "sync-signed-xpi.mjs")], { stdio: "inherit" });
} else {
  console.log("[sign] ensuring signed xpi for the current version…");
  execFileSync(process.execPath, [join(root, "scripts", "amo-sign.mjs")], { stdio: "inherit" });
}
const extensionVersion = JSON.parse(readFileSync(join(root, "dist", "extension", "manifest.json"), "utf8")).version;

// The interactive installer is a single Go binary (replaces the per-OS shell
// installers). It is built fully self-contained: before compiling, the chrome
// helper payload and the signed add-on xpi are staged into installer/payload/
// and embedded with go:embed, so the shipped binary can do a COMPLETE install
// (profile chrome files, user.js merge, signed add-on install, loader) with no
// repo checkout, no dist/ folder and no toolchain. Build it for every supported
// platform into installer/bin/ so releases ship one native binary per OS:
//   lazyfox-install-linux, lazyfox-install-darwin, lazyfox-install-windows.exe
const INSTALLER_TARGETS = [
  { goos: "linux", arch: "amd64", out: "lazyfox-install-linux" },
  { goos: "darwin", arch: "arm64", out: "lazyfox-install-darwin" },
  { goos: "windows", arch: "amd64", out: "lazyfox-install-windows.exe" },
];

// Stage the payloads the installer embeds (profile chrome files + user.js, and
// the signed add-on xpi). These are intermediate build inputs only — the
// binaries in installer/bin/ carry the embedded copies — so they are excluded
// from git (see installer/.gitignore). The loader is embedded separately from
// the committed installer/payload/loader/ and is not re-staged here.
const stagePayload = () => {
  const chromeSrc = join(root, "dist", "chrome");
  const chromeDst = join(root, "installer", "payload", "chrome");
  mkdirSync(chromeDst, { recursive: true });
  for (const f of ["userChrome.css", "userChrome.uc.js", "frame.js", "corebootstrap.js", "user.js"]) {
    cpSync(join(chromeSrc, f), join(chromeDst, f));
  }
  // Signed add-on: clear any stale tree staged by older builds, then copy the
  // signed xpi in as the single extension payload.
  const extDst = join(root, "installer", "payload", "extension");
  rmSync(extDst, { recursive: true, force: true });
  mkdirSync(extDst, { recursive: true });
  cpSync(join(root, "dist", `lazyfox2-${extensionVersion}.xpi`), join(extDst, "lazyfox2.xpi"));
  console.log(`[installer] staged payloads -> installer/payload/chrome + extension/lazyfox2.xpi (v${extensionVersion})`);
};

stagePayload();
mkdirSync(join(root, "installer", "bin"), { recursive: true });
for (const t of INSTALLER_TARGETS) {
  const out = join(root, "installer", "bin", t.out);
  execFileSync(
    "go",
    ["build", "-trimpath", "-ldflags=-s -w", "-o", out, "."],
    { cwd: join(root, "installer"), env: { ...process.env, GOOS: t.goos, GOARCH: t.arch }, stdio: "inherit" }
  );
  console.log(`[installer] ${t.goos}/${t.arch} -> installer/bin/${t.out}`);
}

console.log("\nBuild complete. dist/ is ready to install.");
