#!/usr/bin/env node
// Build pipeline for Lazyfox.
//
//   1. Compile the Go core to core/js/core.wasm, base64 it, and write
//      src/shared/wasm-embed.ts (gitignored; the wasm is embedded into every
//      bundle so each context is self-contained). The wasm is embedded raw (no
//      gzip): decompression would need DecompressionStream/pako, which are not
//      guaranteed in every context, whereas atob() + WebAssembly.instantiate()
//      are.
//   2. esbuild-bundle each TypeScript entry (chrome helper, core bootstrap,
//      frame script, content script, background, command center, options x2,
//      popup) into dist/.
//   3. Copy static assets (manifest, HTML pages, icons, chrome css/user.js/
//      loader) from src/static/ into dist/.
//
// dist/ is committed to the repo so installers consume prebuilt output and
// users who clone don't need a Go toolchain to install.

import { spawnSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";
import { zipStore } from "./scripts/amo-lib.ts";
import { buildInstallerSet, type InstallerTarget } from "./scripts/installer-build.ts";
import { TARGETS } from "./scripts/payload.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)));

// `node build.ts --dev` (npm run build) defines __DEV__=true so the dev-only
// diagnostics compile in; the release build (npm run build:release) tree-shakes
// them out entirely (__DEV__=false), keeping dist/ free of debug output.
const DEV = process.argv.includes("--dev");

interface Bundle {
  in: string;
  out: string;
  // "esm" is required for the two JS window actor modules: Firefox imports the
  // file as a module and looks for the exported class by name (LazyfoxChild /
  // LazyfoxParent). Left unminified so an actor failure is readable in the
  // browser console.
  format?: "iife" | "esm";
  minify?: boolean;
}

const BUNDLES: Bundle[] = [
  { in: "src/chrome/main.ts", out: "dist/chrome/userChrome.uc.js" },
  { in: "src/chrome/corebootstrap.ts", out: "dist/chrome/corebootstrap.js" },
  { in: "src/chrome/frame.ts", out: "dist/chrome/frame.js" },
  { in: "src/chrome/actor-boot.ts", out: "dist/chrome/actor-boot.js", minify: false },
  { in: "src/chrome/actor-child.ts", out: "dist/chrome/lazyfox-child.sys.mjs", format: "esm", minify: false },
  { in: "src/chrome/actor-parent.ts", out: "dist/chrome/lazyfox-parent.sys.mjs", format: "esm", minify: false },
  { in: "src/extension/content/main.ts", out: "dist/extension/content.js" },
  { in: "src/extension/background.ts", out: "dist/extension/background.js" },
  { in: "src/extension/commandcenter.ts", out: "dist/extension/commandcenter.js" },
  { in: "src/extension/relay.ts", out: "dist/extension/relay.js" },
  { in: "src/extension/splitpanel.ts", out: "dist/extension/splitpanel.js" },
  { in: "src/extension/options.ts", out: "dist/extension/options.js" },
  { in: "src/extension/optionskeys.ts", out: "dist/extension/optionskeys.js" },
  { in: "src/extension/popup.ts", out: "dist/extension/popup.js" },
  { in: "src/extension/setup.ts", out: "dist/extension/setup.js" },
  { in: "src/extension/diagnostics.ts", out: "dist/extension/diagnostics.js" },
];

/* ---------- 1. wasm core ---------- */

const wasmOut = join(root, "core", "js", "core.wasm");
console.log("[wasm] building core.wasm (GOOS=js GOARCH=wasm)...");
run("go", ["build", "-ldflags=-s -w", "-o", wasmOut, "./core/js"], {
  cwd: root,
  env: { ...process.env, GOOS: "js", GOARCH: "wasm" },
});
const wasmBytes = readFileSync(wasmOut);
const b64 = wasmBytes.toString("base64");
writeFileSync(
  join(root, "src", "shared", "wasm-embed.ts"),
  "// GENERATED by build.ts from core/js/core.wasm \u2014 do not edit.\n" +
    "// base64-encoded (raw, not gzip) so every bundle is self-contained and\n" +
    "// the runtime needs only atob() + WebAssembly.instantiate().\n" +
    "export const WASM_BASE64 =\n  \"" +
    b64 +
    "\";\n"
);
console.log(
  `[wasm] ${wasmBytes.length} bytes -> base64 ${b64.length}`
);

/* ---------- 2. esbuild bundles ---------- */

for (const b of BUNDLES) {
  const outfile = join(root, b.out);
  mkdirSync(dirname(outfile), { recursive: true });
  await build({
    entryPoints: [join(root, b.in)],
    bundle: true,
    outfile,
    format: b.format || "iife",
    platform: "browser",
    target: ["firefox115"],
    define: { __DEV__: DEV ? "true" : "false" },
    minify: b.minify !== false,
    logLevel: "info",
  });
  console.log(`[bundle] ${b.in} -> ${b.out}`);
}

/* ---------- 3. static assets ---------- */

cpSync(join(root, "src", "static", "extension"), join(root, "dist", "extension"), {
  recursive: true,
});
cpSync(join(root, "src", "static", "chrome"), join(root, "dist", "chrome"), {
  recursive: true,
});
console.log("[static] src/static/{extension,chrome} -> dist/");

/* ---------- 3b. native messaging host ---------- */

// Build the Go native host (native-host/) for the CURRENT platform into
// build/native-host/. The installer writes the matching native-messaging
// manifest (lazyfox.json) into the OS-native location during install, so the
// extension's host.ts client can reach it (see docs/MESSAGING.md, Stage 2).
// The host is OPTIONAL at runtime — AMO/store installs without the installer's
// host step degrade cleanly — so this step never blocks the extension build.
{
  const hostDir = join(root, "build", "native-host");
  mkdirSync(hostDir, { recursive: true });
  const out = join(hostDir, process.platform === "win32" ? "lazyfox-host.exe" : "lazyfox-host");
  console.log(`[native-host] building lazyfox-host for ${process.platform}/${process.arch}…`);
  try {
    run("go", ["build", "-trimpath", "-ldflags=-s -w", "-o", out, "."], {
      cwd: join(root, "native-host"),
    });
    console.log(`[native-host] ${out}`);
  } catch (e) {
    console.warn("[native-host] build failed (host is optional; skipping): " + String(e instanceof Error && e.message ? e.message : e));
  }
}

/* ---------- 4. dev add-on / signed add-on + installer binary ---------- */

// In --dev mode we skip the production release steps (AMO signing and the
// cross-platform RELEASE binaries). We do NOT skip the installer entirely: this
// platform's dev installer is rebuilt from the fresh payload (see below). A dev
// build that left the installer binary stale is exactly how a launched installer
// ends up erroring or installing an old chrome layer.
if (DEV) {
  const version = JSON.parse(readFileSync(join(root, "dist", "extension", "manifest.json"), "utf8")).version;
  const unsignedOut = join(root, "dist", `lazyfox2-${version}.xpi`);
  console.log(`[dev] packaging unsigned xpi -> dist/lazyfox2-${version}.xpi`);
  zipStore(join(root, "dist", "extension"), unsignedOut);

  // Refresh the dev installers so the binaries in installer/bin/ are always the
  // ones this build produced — the embedded payload can never be last week's.
  //
  // This used to rebuild only THIS platform's binary, which meant a plain
  // `npm run build` on Windows quietly left the committed linux and darwin
  // installers carrying the previous build: the tree looked "built", and anyone
  // who grabbed those two got old code. The rule is now the simple one — after
  // a build, every committed executable matches the tree, or the build failed.
  //
  // The other targets are cross-compiled terminal installers (no webview, no
  // CGO), so this costs a couple of extra compiles rather than a second
  // machine. Set LF_INSTALLER_TARGETS=host to build only this machine's binary
  // when iterating in a hurry and nothing else consumes installer/bin/.
  //
  // This is a hard step on purpose: `npm run build` already needs the Go
  // toolchain for the wasm core, so a failure here means the installer really
  // is broken and silently shipping a stale binary is the bug we are fixing.
  console.log("\n[installer] refreshing the dev installers with the fresh payload…");
  run(process.execPath, [join(root, "scripts", "build-dev-installers.ts")], {
    cwd: root,
  });

  // The RELEASE installers embed an AMO-signed add-on, so they can only be rebuilt
  // when a signed xpi exists (stable Firefox refuses an unsigned one). When one
  // does, they are refreshed here too — with the CURRENT chrome layer and the
  // last signed add-on — so a plain build never leaves a committed binary
  // carrying an old payload. When none exists they are left alone, and the
  // reason is printed rather than left to be discovered later.
  const signedXpis = existsSync(join(root, "dist"))
    ? readdirSync(join(root, "dist")).filter((f) => /^lazyfox2-.*-signed\.xpi$/.test(f))
    : [];
  if (signedXpis.length > 0) {
    console.log("\n[installer] refreshing the release installers (signed add-on: …" + signedXpis[signedXpis.length - 1] + ")…");
    run(process.execPath, [join(root, "scripts", "build-release-installers.ts")], { cwd: root });
  } else {
    console.log(
      "\n[installer] no signed add-on in dist/ yet, so the release installers were left alone:\n" +
        "  they carry the last signed build, which is correct for their channel. Sign one\n" +
        "  with `npm run submit` (or run `npm run build:release`) to refresh them.",
    );
  }

  console.log(`\nBuild complete. dist/ is ready to install (unsigned dev add-on).`);
  console.log("Every committed installer was rebuilt from this payload — `npm run check` prints the table.");
  process.exit(0);
}

// `npm run build:installers` (node scripts/build-dev-installers.ts) rebuilds the
// committed per-OS DEV installer binaries (they embed the unsigned xpi), and is
// what `npm run build` calls — so the standalone command and the build cannot
// disagree about what a dev installer is. Running it on its own is for the
// cases a build does not cover: a dist/ change that did not come from a build
// (a hand-edited loader, a synced signed xpi), or rebuilding every platform
// from a checkout whose host binary is already current. The dev install flow
// itself is `npm run dev-install`.

// Ensure a signed .xpi exists for the current extension version.
//
// Release mode (RELEASE=1, used by the master workflow): sync-signed-xpi.ts
// downloads the AMO-signed xpi for the exact manifest version from AMO and
// writes both dist/lazyfox2-<ver>.xpi and -signed.xpi. It reuses a committed
// signed xpi when already current, so it is deterministic (version comes from
// the manifest) and never fabricates or guesses.
//
// Normal mode: amo-sign.ts reuses the committed signed artifact offline, or
// auto-submits a NEW version to AMO when the version is bumped (see that script
// for details). The installer installs this signed xpi verbatim, which is what
// makes the add-on load on stable Firefox (it already ships the AMO signature
// block).
if (process.env.RELEASE === "1") {
  console.log("[sign] syncing AMO-signed xpi for the current version…");
  const sync = spawnSync(process.execPath, [join(root, "scripts", "sync-signed-xpi.ts")], { stdio: "inherit" });
  if (sync.status !== 0) {
    // sync-signed-xpi.ts already printed the reason. Fail gently instead of
    // letting the raw child-process error bubble up as a stack trace.
    console.error(
      "\nRelease build stopped: the AMO-signed xpi for this version is not available yet.\n" +
        "  • This command (`npm run build:release`) is ONLY for the master release workflow.\n" +
        "  • If you are developing on dev-nightly, use `npm run build` (unsigned dev build) instead.\n" +
        "  • To release, first submit this version on AMO (see docs/RELEASING.md), wait for it to be\n" +
        "    reviewed & signed, then run this from master."
    );
    process.exit(1);
  }
} else {
  console.log("[sign] ensuring signed xpi for the current version…");
  serverRun(process.execPath, [join(root, "scripts", "amo-sign.ts")]);
}
const extensionVersion = JSON.parse(readFileSync(join(root, "dist", "extension", "manifest.json"), "utf8")).version;

// The interactive installer is a single Go binary (replaces the per-OS shell
// installers). It is built fully self-contained: before compiling, the chrome
// helper payload and the signed add-on xpi are staged into
// installer/internal/payload/data/ (beside the package that embeds them — Go
// resolves //go:embed relative to the package dir) and embedded with go:embed,
// so the shipped binary can do a COMPLETE install
// (profile chrome files, user.js merge, signed add-on install, loader) with no
// repo checkout, no dist/ folder and no toolchain. Build it for every supported
// platform into installer/bin/ so releases ship one native binary per OS:
//   lazyfox-install-linux, lazyfox-install-darwin, lazyfox-install-windows.exe
const INSTALLER_TARGETS: InstallerTarget[] = TARGETS.map((t) => ({
  goos: t.goos,
  arch: t.arch,
  out: t.releaseOut,
}));

// Stage the payloads the installer embeds and compile every target — through
// the SAME function the dev installers use (scripts/installer-build.ts), so the
// two can never stage different files. The chrome list lives there too.
//
// These staged files are intermediate build inputs only: the binaries in
// installer/bin/ carry the embedded copies, so they are gitignored. The loader
// is embedded separately from the committed internal/payload/data/loader/.
//
// `dist/lazyfox2-<version>.xpi` is the canonical add-on: amo-sign.ts above has
// made it the signed artifact for this version (or, failing that, left the most
// recent committed signed xpi in its place and said so).
buildInstallerSet({
  root,
  installerDir: join(root, "installer"),
  targets: INSTALLER_TARGETS,
  // The RELEASE installers carry the signed build and target stable Firefox;
  // the dev installers (scripts/build-dev-installers.ts) stamp "nightly".
  channel: "stable",
  xpiPath: join(root, "dist", `lazyfox2-${extensionVersion}.xpi`),
  version: extensionVersion,
  logPrefix: "[installer]",
});

console.log("\nBuild complete. dist/ is ready to install.");

/* ---------- helpers ---------- */

// run executes a command, streaming output to the parent, and throws a readable
// error (instead of a raw stack trace) if it fails. Used for build steps where a
// failure is a normal, explainable outcome.
function run(
  cmd: string,
  args: string[],
  opts?: { cwd?: string; env?: NodeJS.ProcessEnv }
): void {
  const res = spawnSync(cmd, args, { stdio: "inherit", ...opts });
  if (res.error) {
    throw new Error(`failed to run ${cmd}: ${res.error.message}`);
  }
  if (res.status !== 0) {
    throw new Error(`${cmd} exited with code ${res.status}`);
  }
}

// serverRun is the same as run but swallows non-zero exits (used where a child
// script already printed its own reason and a failure is a soft signal).
function serverRun(
  cmd: string,
  args: string[],
  opts?: { cwd?: string; env?: NodeJS.ProcessEnv }
): void {
  spawnSync(cmd, args, { stdio: "inherit", ...opts });
}
