#!/usr/bin/env bash
# Lazyfox full-install patcher (GENERATED by build.mjs - do not edit).
#
# Complements the AMO WebExtension: the store add-on cannot write files itself,
# so this self-contained script applies the other half of Lazyfox:
#   1. the profile patch - chrome/userChrome.css, userChrome.uc.js, frame.js,
#      corebootstrap.js (backed up; only Lazyfox's own files are touched),
#   2. the user.js pref merge (only the prefs Lazyfox owns; yours are kept),
#   3. the fx-autoconfig chrome loader (config.js + config-prefs.js) in the
#      Firefox install directory - one sudo prompt, once (skip with --skip-loader).
#
# The WebExtension itself is already installed (from addons.mozilla.org); this
# script never touches your bookmarks, history or other add-ons. Fully quit and
# restart Firefox afterwards to apply everything.
#
# Usage:  bash ./lazyfox-install.sh
#         bash ./lazyfox-install.sh --profile "/path/to/profile"
#         bash ./lazyfox-install.sh --skip-loader
set -u

PROFILE=""
FF_DIR=""
SKIP_LOADER=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile) PROFILE="$2"; shift 2 ;;
    --firefox-dir) FF_DIR="$2"; shift 2 ;;
    --skip-loader) SKIP_LOADER=1; shift ;;
    *) echo "unknown option: $1"; exit 1 ;;
  esac
done

step() { echo "==> $*" ; }
warn() { echo "WARNING: $*" >&2 ; }

# ---------- embedded payload (filled by build.mjs) ----------
B64_userChrome_css="__B64_userChrome_css__"
B64_userChrome_uc_js="__B64_userChrome_uc_js__"
B64_frame_js="__B64_frame_js__"
B64_corebootstrap_js="__B64_corebootstrap_js__"
B64_user_js="__B64_user_js__"
B64_loader_config_js="__B64_loader_config_js__"
B64_loader_config_prefs_js="__B64_loader_config_prefs_js__"

b64_decode() { # base64 -d on Linux, base64 -D on macOS
  if base64 -d </dev/null >/dev/null 2>&1; then base64 -d
  else base64 -D; fi
}

write_file() { # $1=path $2=base64
  mkdir -p "$(dirname "$1")"
  printf '%s' "$2" | b64_decode > "$1"
}

backup() { # $1=path
  if [[ -e "$1" ]]; then
    cp -f "$1" "$1.lazyfox.bak-$(date +%Y%m%d-%H%M%S)" 2>/dev/null
  fi
}

find_firefox() {
  for c in firefox firefox-dev firefox-nightly firefox-esr; do
    if command -v "$c" >/dev/null 2>&1; then echo "$(command -v "$c")"; return; fi
  done
  for p in \
    /usr/lib/firefox/firefox /opt/firefox/firefox \
    /Applications/Firefox.app/Contents/MacOS/firefox \
    "/Applications/Firefox Developer Edition.app/Contents/MacOS/firefox" \
    "/Applications/Firefox Nightly.app/Contents/MacOS/firefox"; do
    if [[ -x "$p" ]]; then echo "$p"; return; fi
  done
  echo ""
}

# Find the profile to patch: prefer the one with THIS store add-on installed
# (extensions/<guid>.xpi), then Developer Edition, then the default profile,
# then any profile (same preference order as the repo installer).
resolve_profile() {
  local base="${MOZ_FIREFOX_HOME:-$HOME/.mozilla}"
  local ini="" dir=""
  for d in "$base/firefox" "$base/firefox-dev-edition" "$base/firefox-nightly"; do
    if [[ -f "$d/profiles.ini" ]]; then ini="$d/profiles.ini"; dir="$d"; break; fi
  done
  [[ -z "$ini" ]] && { echo ""; return; }
  local cur="" path="" def="0" dev="0"
  local first="" devp="" defp=""
  flush() {
    [[ -z "$cur" || -z "$path" ]] && return
    local full="$path"
    [[ "$full" != /* ]] && full="$dir/$path"
    if [[ -f "$full/extensions/lazyfox@lazyfox.dev.xpi" ]]; then echo "$full"; exit_early=1; return; fi
    [[ -z "$first" ]] && first="$full"
    [[ "$dev" = "1" && -z "$devp" ]] && devp="$full"
    [[ "$def" = "1" && -z "$defp" ]] && defp="$full"
  }
  local exit_early=0
  while IFS= read -r line; do
    line="${line%%$'\r'}"
    if [[ "$line" =~ ^\[(Profile[0-9]+)\]$ ]]; then
      flush
      [[ "$exit_early" = "1" ]] && return
      cur="$line"; path=""; def="0"; dev="0"
    elif [[ "$line" =~ ^Path=(.+)$ ]]; then path="${BASH_REMATCH[1]}"
    elif [[ "$line" =~ ^Default=1$ ]]; then def="1"
    elif [[ "$line" =~ dev-edition ]]; then dev="1"
    fi
  done < "$ini"
  flush
  [[ "$exit_early" = "1" ]] && return
  echo "${devp:-${defp:-$first}}"
}

install_chrome_files() { # $1=profile dir
  local chrome="$1/chrome"
  local spec name b64
  for spec in \
    "userChrome.css:$B64_userChrome_css" \
    "userChrome.uc.js:$B64_userChrome_uc_js" \
    "frame.js:$B64_frame_js" \
    "corebootstrap.js:$B64_corebootstrap_js"; do
    name="${spec%%:*}"; b64="${spec#*:}"
    backup "$chrome/$name"
    write_file "$chrome/$name" "$b64"
  done
  step "Installed chrome/userChrome.css, userChrome.uc.js, frame.js, corebootstrap.js"
}

merge_user_js() { # $1=profile dir
  local user_js="$1/user.js" ours line pref
  ours="$(printf '%s' "$B64_user_js" | b64_decode)"
  backup "$user_js"
  local kept=()
  if [[ -f "$user_js" ]]; then
    while IFS= read -r line; do
      if [[ "$line" =~ ^user_pref\(\"([^\"]+)\" ]]; then
        pref="${BASH_REMATCH[1]}"
        if grep -qF "user_pref(\"$pref\"" <<<"$ours"; then continue; fi
      fi
      kept+=("$line")
    done < "$user_js"
  fi
  printf '%s\n' "${kept[@]}" > "$user_js"
  printf '%s\n' "$ours" >> "$user_js"
  step "Merged preferences into user.js"
}

install_loader() { # $1=firefox install dir
  [[ -z "$1" || ! -d "$1" ]] && { warn "could not find the Firefox installation folder: '$1'"; return 1; }
  write_file "$1/config.js" "$B64_loader_config_js"
  write_file "$1/defaults/pref/config-prefs.js" "$B64_loader_config_prefs_js"
  return 0
}

if [[ -n "$PROFILE" ]]; then profile="$PROFILE"
else profile="$(resolve_profile)"; fi
if [[ -z "$profile" || ! -d "$profile" ]]; then
  echo "Could not find a Firefox profile automatically."
  echo "Open Firefox, go to about:support and copy the 'Profile Folder' path, then run:"
  echo "  bash ./lazyfox-install.sh --profile \"/path/to/profile\""
  exit 1
fi
step "Profile: $profile"

install_chrome_files "$profile"
merge_user_js "$profile"

if [[ "$SKIP_LOADER" = "0" ]]; then
  ff_dir="${FF_DIR:-}"
  if [[ -z "$ff_dir" ]]; then
    local_ff="$(find_firefox)"
    [[ -n "$local_ff" ]] && ff_dir="$(dirname "$local_ff")"
  fi
  if [[ -n "$ff_dir" ]]; then
    if [[ ! -f "$ff_dir/config.js" || ! -f "$ff_dir/defaults/pref/config-prefs.js" ]]; then
      if [[ -w "$ff_dir" ]]; then
        install_loader "$ff_dir" && step "Chrome loader installed."
      else
        step "Installing the chrome loader into $ff_dir requires root (one-time sudo prompt)."
        sudo -p "Lazyfox needs admin rights once to install the chrome loader: " \
          bash -c 'set -e; mkdir -p "$1/defaults/pref"; if base64 -d </dev/null >/dev/null 2>&1; then DEC=base64\ -d; else DEC=base64\ -D; fi; printf "%s" "$2" | $DEC > "$1/config.js"; printf "%s" "$3" | $DEC > "$1/defaults/pref/config-prefs.js"' \
          bash "$ff_dir" "$B64_loader_config_js" "$B64_loader_config_prefs_js" \
          && step "Chrome loader installed." \
          || warn "chrome loader was not installed (root required). Re-run from a shell with write access to $ff_dir, or pass --skip-loader."
      fi
    else
      echo "NOTE: chrome loader already installed in $ff_dir"
    fi
  else
    warn "could not locate firefox; chrome loader not installed (internal-page ; keys won't work). Pass --firefox-dir to fix."
  fi
fi

echo ""
echo "Done. Fully quit and restart Firefox to apply the changes."
echo "  - The toolbar-free UI (tabs/URL bar hidden), the status bar and chrome-level ; keys now work."
echo "  - Nothing of yours was touched: only Lazyfox files were written, each with a .lazyfox.bak-* backup."
