# Lazyfox full-install patcher (GENERATED by build.mjs - do not edit).
#
# Complements the AMO WebExtension: the store add-on cannot write files itself,
# so this self-contained script applies the other half of Lazyfox:
#   1. the profile patch - chrome/userChrome.css, userChrome.uc.js, frame.js,
#      corebootstrap.js (backed up, only Lazyfox's own files are touched),
#   2. the user.js pref merge (only the prefs Lazyfox owns; yours are kept),
#   3. the fx-autoconfig chrome loader (config.js + config-prefs.js) in the
#      Firefox install directory - one UAC prompt, once (skip with -SkipLoader).
#
# The WebExtension itself is already installed (from addons.mozilla.org); this
# script never touches your bookmarks, history or other add-ons. Fully quit and
# restart Firefox afterwards to apply everything.
#
# Usage:  powershell -ExecutionPolicy Bypass -File .\lazyfox-install.ps1
#         powershell -ExecutionPolicy Bypass -File .\lazyfox-install.ps1 -Profile "C:\path\to\profile"
#         powershell -ExecutionPolicy Bypass -File .\lazyfox-install.ps1 -SkipLoader

param(
  [string]$Profile = "",
  [string]$FirefoxDir = "",
  [switch]$ChromeLoaderOnly,
  [switch]$SkipLoader
)

$ErrorActionPreference = "Stop"

function Write-Step { param([string]$Msg) Write-Host "==> $Msg" -ForegroundColor Cyan }
function Write-Warn { param([string]$Msg) Write-Host "WARNING: $Msg" -ForegroundColor Yellow }
function Write-Note { param([string]$Msg) Write-Host "NOTE: $Msg" -ForegroundColor DarkGray }

# ---------- embedded payload (filled by build.mjs) ----------
$B64 = @{
  userChrome_css        = "__B64_userChrome_css__"
  userChrome_uc_js      = "__B64_userChrome_uc_js__"
  frame_js              = "__B64_frame_js__"
  corebootstrap_js      = "__B64_corebootstrap_js__"
  user_js               = "__B64_user_js__"
  loader_config_js      = "__B64_loader_config_js__"
  loader_config_prefs_js = "__B64_loader_config_prefs_js__"
}

function Write-B64File {
  param([string]$Path, [string]$B64)
  New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Path) | Out-Null
  $bytes = [Convert]::FromBase64String($B64)
  $utf8NoBom = New-Object System.Text.UTF8Encoding $false
  [System.IO.File]::WriteAllText($Path, $utf8NoBom.GetString($bytes), $utf8NoBom)
}

# Backup a file we are about to overwrite (kept 30 days by the user).
function Backup-Existing {
  param([string]$Path)
  if (Test-Path -LiteralPath $Path) {
    Copy-Item -LiteralPath $Path -Destination ($Path + ".lazyfox.bak-" + (Get-Date -Format 'yyyyMMdd-HHmmss')) -Force
  }
}

function Find-FirefoxExe {
  $candidates = @(
    "$env:ProgramFiles\Firefox Developer Edition\firefox.exe",
    "$env:ProgramFiles\Mozilla Firefox Developer Edition\firefox.exe",
    "$env:ProgramFiles\Mozilla Firefox\firefox.exe",
    "${env:ProgramFiles(x86)}\Mozilla Firefox\firefox.exe"
  )
  foreach ($c in $candidates) {
    if (Test-Path -LiteralPath $c) { return $c }
  }
  return ""
}

# Parse profiles.ini exactly like the repo installer, but prefer the profile
# that actually has THIS store add-on installed (extensions\<guid>.xpi).
function Resolve-ProfilePath {
  param([string]$IniPath, [string]$BaseDir)
  $profiles = @()
  if (Test-Path -LiteralPath $IniPath) {
    $ini = Get-Content -LiteralPath $IniPath
    for ($i = 0; $i -lt $ini.Count; $i++) {
      if ($ini[$i] -match '^\[(Profile\d+)\]$') {
        $name = $matches[1]
        $isDefault = $false
        $path = ""
        for ($j = $i + 1; $j -lt $ini.Count; $j++) {
          if ($ini[$j] -match '^\[') { break }
          if ($ini[$j] -match '^Default=1$') { $isDefault = $true }
          if ($ini[$j] -match '^Path=(.+)$') { $path = $matches[1] }
        }
        if ($path) {
          $full = if ([System.IO.Path]::IsPathRooted($path)) { $path } else { Join-Path (Split-Path -Parent $IniPath) $path }
          $profiles += [PSCustomObject]@{
            Name = $name
            IsDefault = $isDefault
            IsDevEdition = ($name -match 'dev-edition') -or ($path -match 'dev-edition')
            FullPath = $full
          }
        }
      }
    }
  }
  # 1) the profile this add-on is installed into
  foreach ($p in $profiles) {
    if (Test-Path -LiteralPath (Join-Path $p.FullPath "extensions\lazyfox@lazyfox.dev.xpi")) { return $p.FullPath }
  }
  # 2) developer edition, 3) the default profile, 4) any .default dir
  $dev = $profiles | Where-Object { $_.IsDevEdition } | Select-Object -First 1
  if ($dev) { return $dev.FullPath }
  $def = $profiles | Where-Object { $_.IsDefault } | Select-Object -First 1
  if ($def) { return $def.FullPath }
  $any = Get-ChildItem -LiteralPath $BaseDir -Directory -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -match "\.default" } | Select-Object -First 1
  if ($any) { return $any.FullName }
  return ""
}

function Test-IsAdmin {
  try {
    $id = [Security.Principal.WindowsIdentity]::GetCurrent()
    $p = New-Object Security.Principal.WindowsPrincipal($id)
    return $p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
  }
  catch { return $false }
}

function Install-ChromeFiles {
  param([string]$ProfileDir)
  $chromeDir = Join-Path $ProfileDir "chrome"
  New-Item -ItemType Directory -Force -Path $chromeDir | Out-Null
  $files = @(
    @("userChrome.css", $B64.userChrome_css),
    @("userChrome.uc.js", $B64.userChrome_uc_js),
    @("frame.js", $B64.frame_js),
    @("corebootstrap.js", $B64.corebootstrap_js)
  )
  foreach ($f in $files) {
    $dest = Join-Path $chromeDir $f[0]
    Backup-Existing $dest
    Write-B64File $dest $f[1]
  }
  Write-Step "Installed chrome\userChrome.css, userChrome.uc.js, frame.js, corebootstrap.js"
}

# Merge user.js: drop only the lines whose pref Lazyfox owns, append ours.
function Merge-UserJs {
  param([string]$ProfileDir)
  $managed = @{}
  $ourContent = [System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($B64.user_js)) -split "`r?`n"
  foreach ($line in $ourContent) {
    if ($line -match '^user_pref\("([^"]+)"') { $managed[$matches[1]] = $true }
  }
  $userJs = Join-Path $ProfileDir "user.js"
  Backup-Existing $userJs
  $kept = @()
  if (Test-Path -LiteralPath $userJs) {
    $kept = Get-Content -LiteralPath $userJs | Where-Object {
      if ($_ -match '^user_pref\("([^"]+)"') { -not $managed.ContainsKey($matches[1]) }
      else { $true }
    }
  }
  $utf8NoBom = New-Object System.Text.UTF8Encoding $false
  [System.IO.File]::WriteAllLines($userJs, @($kept) + @($ourContent), $utf8NoBom)
  Write-Step "Merged preferences into user.js"
}

function Install-ChromeLoader {
  param([string]$Dir)
  if (-not $Dir -or -not (Test-Path -LiteralPath $Dir)) {
    Write-Warn "could not find the Firefox installation folder: '$Dir'"
    return $false
  }
  Write-B64File (Join-Path $Dir "config.js") $B64.loader_config_js
  Write-B64File (Join-Path $Dir "defaults\pref\config-prefs.js") $B64.loader_config_prefs_js
  return $true
}

if ($ChromeLoaderOnly) {
  if (Install-ChromeLoader $FirefoxDir) {
    Write-Step "Chrome loader installed into $FirefoxDir"
    exit 0
  }
  exit 1
}

$profileDir = ""
if ($Profile) { $profileDir = $Profile }
else {
  $firefoxData = Join-Path $env:APPDATA "Mozilla\Firefox"
  $profileDir = Resolve-ProfilePath (Join-Path $firefoxData "profiles.ini") (Join-Path $firefoxData "Profiles")
}
if (-not $profileDir -or -not (Test-Path -LiteralPath $profileDir)) {
  Write-Host "Could not find a Firefox profile automatically."
  Write-Host "Open Firefox, go to about:support and copy the 'Profile Folder' path, then run:"
  Write-Host "  powershell -ExecutionPolicy Bypass -File .\lazyfox-install.ps1 -Profile `"C:\path\to\profile`""
  exit 1
}
Write-Step "Profile: $profileDir"

Install-ChromeFiles $profileDir
Merge-UserJs $profileDir

if (-not $SkipLoader) {
  $ff = Find-FirefoxExe
  $ffDir = if ($ff) { Split-Path -Parent $ff } else { "" }
  if ($ffDir -and $FirefoxDir) { $ffDir = $FirefoxDir }
  elseif (-not $ffDir) { $ffDir = $FirefoxDir }
  if ($ffDir) {
    $cfg = Join-Path $ffDir "config.js"
    $pref = Join-Path $ffDir "defaults\pref\config-prefs.js"
    $need = (-not (Test-Path -LiteralPath $cfg)) -or (-not (Test-Path -LiteralPath $pref))
    if ($need) {
      if (-not (Test-IsAdmin)) {
        Write-Step "Installing the chrome loader into $ffDir requires administrator rights (one-time)."
        Write-Step "A UAC prompt may appear - accept it to install config.js + config-prefs.js."
        $args = "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`" -ChromeLoaderOnly -FirefoxDir `"$ffDir`""
        $p = Start-Process -FilePath "powershell.exe" -ArgumentList $args -Verb RunAs -Wait -PassThru
        if ($p.ExitCode -ne 0) {
          Write-Warn "chrome loader was not installed (admin required). Re-run this script from an elevated shell, or pass -SkipLoader."
        }
        else { Write-Step "Chrome loader installed." }
      }
      else {
        if (Install-ChromeLoader $ffDir) { Write-Step "Chrome loader installed." }
      }
    }
    else { Write-Note "Chrome loader already installed in $ffDir" }
  }
  else {
    Write-Warn "could not locate firefox.exe; chrome loader not installed (internal-page ; keys won't work). Pass -FirefoxDir to fix."
  }
}

Write-Host ""
Write-Host "Done. Fully quit and restart Firefox to apply the changes."
Write-Host "  - The toolbar-free UI (tabs/URL bar hidden), the status bar and chrome-level ; keys now work."
Write-Host "  - Nothing of yours was touched: only Lazyfox files were written, each with a .lazyfox.bak-* backup."
